apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
<<<<<<< HEAD
        image: europe-west4-docker.pkg.dev/qwiklabs-gcp-01-05bdc8c7ffef/my-repository/sample-app:v1.0
=======
        image: <todo>
>>>>>>> parent of 310d36e (Initial prod deployment v1.0)
        ports:
        - containerPort: 8080
